# Generated by Django 6.0.4 on 2026-04-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Time')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('ano_fundacao', models.IntegerField(verbose_name='Ano de Fundação')),
            ],
        ),
    ]
